version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: django-app
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
