# Generated by Django 5.2 on 2025-05-12 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cartitem_delete_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'verbose_name': 'Цена товара в магазине', 'verbose_name_plural': 'Цены товаров по магазинам'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='author_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Имя отправителя'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='pricesuggestion',
            name='suggested_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Предложенная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
