# Generated by Django 5.2 on 2025-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_cartitem_unique_together_cartitem_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('delivering', 'Доставляется'), ('delivered', 'Доставлен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
