# Generated by Django 5.2 on 2025-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_order_address_order_full_name_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Картой при получении'), ('cash', 'Наличными')], default='card', max_length=10, verbose_name='Способ оплаты'),
        ),
    ]
